### ISSUE TITLE
[W513] "gulpfile.js" found in repo! incorrect for react based ui

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/ioBroker.repochecker#223]
👀 [W513] "gulpfile.js" found in repo! Think about migrating to @iobroker/adapter-dev package
is incorrect if the adapter uses react.

see #222 too

**Comment by mcm1957** [comment]
Kriterium für react
im admin Verzeichnis sollte das Verzeichnis "static und / oder "custom" existieren

https://forum.iobroker.net/topic/74579/meeting-f%C3%BCr-iobroker-core-dev-admin-19-06-24-20-30/7

**Comment by mcm1957** [comment]
fixed with 2.6.0

**Comment by simatec** [comment]
Unfortunately, the warning [W513] still appears in the current check on iobroker.dev

![image](https://github.com/user-attachments/assets/f3b4c94e-f4dc-4613-8d83-c53504421728)

**Comment by mcm1957** [comment]
The webbased checker is outdated. Please use commandline (npw) or bot.

Web based checker requires rebuild of iobroker.dev webpages which can only be done by few people. iobroker.dev should be adapter to use the latest (or an easy to change) version of @iobroker/repochecker - but this is a issue for iobroker.dev web system

**Comment by simatec** [comment]
This should then be adjusted promptly. It is becoming increasingly difficult for developers to see through what is still current and what is not. I think the Repochecker from iobroker.dev should always be identical to the CLI. 

Anything else will only cause more confusion and at some point, out of desperation, one or two developers will move on to other projects

**Comment by mcm1957** [comment]
I confirm the goal. Yes webpage should use same checks. But as far as I know currently has time / knowlegde to adjust iobroker.dev website.

If you know someone to adapt the webpage he / she is welcome. I neither have access nor knowledge with frontent programming. 

Feel free to open a issue at https://github.com/ioBroker/dev-portal.
